# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180315_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
