# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180315_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='awards',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='limited',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AddField(
            model_name='project',
            name='sponsor_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.TextField(null=True),
        ),
    ]
